# Generated by Django 2.2.5 on 2022-02-19 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0005_auto_20220218_2204'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='pending', max_length=12)),
                ('guest', models.ForeignKey(on_delete='cascade', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete='cascade', to='rooms.Room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
